name: Docker CI/CD script

on:
#  TODO: Remove below 3 lines when merge into main!!
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#          TODO: REMOVE THIS!!
      - name: Debugging1
        run: ls -al

      - name: Access ENV
        run: echo '${{ secrets.ENV }}' > ./.env


          #          TODO: REMOVE THIS!!
      - name: Debugging2
        run: ls -al

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./dockerfile
          tags: jja08111/camstudy-media-server:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_IP_ADDRESS }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          debug: true
          port: 22
          script: |
            cd ~/camstudy-webrtc-server
            sudo docker login
            sudo docker pull jja08111/camstudy-media-server:latest
            sudo docker stop camstudy_media_server
            sudo docker rm camstudy_media_server
            sudo docker run -d --name camstudy_media_server -p 2000-2020:2000-2020 jja08111/camstudy-media-server:latest
            echo "success";
